#ifndef NETWORK_SYNC_BUILD_CONFIG_H
#define NETWORK_SYNC_BUILD_CONFIG_H

#ifndef APP_NETWORK_SYNC_TIME_SYNC_RETRY_MS
#define APP_NETWORK_SYNC_TIME_SYNC_RETRY_MS          5000UL
#endif

#ifndef APP_NETWORK_SYNC_TIME_SYNC_PERIOD_MS
#define APP_NETWORK_SYNC_TIME_SYNC_PERIOD_MS         (6UL * 60UL * 60UL * 1000UL)
#endif

#ifndef APP_NETWORK_SYNC_TIME_SYNC_WAIT_MS
#define APP_NETWORK_SYNC_TIME_SYNC_WAIT_MS           0U
#endif


#ifndef APP_NETWORK_SYNC_WEATHER_RETRY_MS
#define APP_NETWORK_SYNC_WEATHER_RETRY_MS            60000UL
#endif

#ifndef APP_NETWORK_SYNC_WEATHER_PERIOD_MS
#define APP_NETWORK_SYNC_WEATHER_PERIOD_MS           (30UL * 60UL * 1000UL)
#endif

#ifndef APP_NETWORK_SYNC_WEATHER_CONNECT_TIMEOUT_MS
#define APP_NETWORK_SYNC_WEATHER_CONNECT_TIMEOUT_MS  4000U
#endif

#ifndef APP_NETWORK_SYNC_WEATHER_REQUEST_TIMEOUT_MS
#define APP_NETWORK_SYNC_WEATHER_REQUEST_TIMEOUT_MS  4000U
#endif

#ifndef APP_NETWORK_SYNC_TLS_ALLOW_INSECURE
#define APP_NETWORK_SYNC_TLS_ALLOW_INSECURE          0
#endif

#endif
