#ifndef APP_LIMITS_H
#define APP_LIMITS_H

#define APP_MAX_ALARMS               3U
#define APP_STOPWATCH_LAP_MAX        8U
#define APP_TIMER_PRESET_COUNT       5U
#define APP_POPUP_QUEUE_DEPTH        4U
#define APP_RUNTIME_EVENT_HANDLER_CAPACITY 16U
#define APP_BOOT_LOOP_SAFE_MODE_THRESHOLD  2U

#endif
